### ISSUE TITLE
Wrapper options

### ISSUE THREAD

**Issue by zbeyens** [lindesvard/pushmodal#2]
Great work! I'm considering adopting it in my app.

Firstly, I believe that shadcn components should not be included in the package, as they are intended to be owned by the consumer.

I could use my own components using the ﻿Wrapper option, but it seems there is no way to pass other options to them. For instance, I need to pass ﻿onOpenChange.

https://github.com/lindesvard/pushmodal/blob/main/src/lib/factory.tsx#L123

**Comment by lindesvard** [comment]
Agree with everything basically! Added the components now to get something working. Not sure tho why you need access too `onOpenChange`? Can you elaborate why you need it? Since it's only there for controlling the modal.

**Comment by zbeyens** [comment]
I use it to reset a state on open/close (though we could use a `﻿useEffect` in the content for that case). There are also many other props than `﻿onEscapeKeyDown, ﻿onInteractOutside, ﻿onPointerDownOutside` that could be needed, depending on the wrapper.

**Comment by lindesvard** [comment]
Yes, you should use `useEffect`, much better for that case tbh. I have refactored a bit and remove quite a lot of code now. So `<(Dialog|Sheet|Drawer)Content>` need to be used in your modal component (before it was used inside the lib).

So now you will have full control over styling and all the props for the `Content` component, since all the important props are inside that one!

**Comment by lindesvard** [comment]
Closing this issue now. Latest version is live `pushmodal@0.0.7` and these things are solved there. **Breaking changes tho**
